### ISSUE TITLE
Params with `_in` like `proposal_in` should not be empty arrays

### ISSUE THREAD

**Issue by ChaituVR** [snapshot-labs/snapshot-hub#757]
Right now we return a response even if the user passes empty arrays, I think we should return an error in such cases  

Example query 
```Graphql
query Votes($voter: String!, $proposals: [String]!) {
    votes(first: 1000, where: { voter: $voter, proposal_in: $proposals }) {
      proposal {
        id
        space {
          id
        }
      }
    }
  }
 
  ```
variables
```JSON
{
  "voter": "0x24F15402C6Bb870554489b2fd2049A85d75B982f",
  "proposals": []
}
```

**Comment by ChaituVR** [comment]
Or we should return empty response like here

https://thegraph.com/hosted-service/subgraph/ensdomains/ens
```Graphql
{
  domains(first: 5, where:{labelName_in:[]}) {
    id
    name
    labelName
    labelhash
  }
  
}
```

**Comment by wa0x6e** [comment]
Lens graphql is returning an error like:

```json
{
  "errors": [
    {
      "message": "ownedBy must have at least one EthereumAddress defined",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "profiles"
      ],
      "extensions": {
        "code": "GRAPHQL_VALIDATION_FAILED",
        "exception": {
          "stacktrace": [
            "ValidationError: ownedBy must have at least one EthereumAddress defined",
            "    at ProfileResolver.profiles (/usr/src/app/packages/api-lens/lib/graphql/resolvers/profile/profile-resolver.js:118:23)",
            "    at /usr/src/app/node_modules/type-graphql/dist/resolvers/create.js:31:98",
            "    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"
          ]
        }
      }
    }
  ],
  "data": null
}
```
